classDiagram

class PresentationLayer {
    +API
    +Services
}

class BusinessLogicLayer {
    +Facade
    +User
    +Place
    +Review
    +Amenity
}

class PersistenceLayer {
    +Repositories
    +Database
}

PresentationLayer --> BusinessLogicLayer : Facade calls
BusinessLogicLayer --> PersistenceLayer : Data access
