classDiagram

class BaseModel {
    +UUID id
    +datetime created_at
    +datetime updated_at
    +save()
    +to_dict()
}

class User {
    +String email
    +String password
    +String first_name
    +String last_name
    +create_place()
    +create_review()
}

class Place {
    +String name
    +String description
    +Float price_per_night
    +Float latitude
    +Float longitude
    +create_review()
    +add_amenity()
}

class Review {
    +String text
    +Integer rating
}

class Amenity {
    +String name
}

BaseModel <|-- User
BaseModel <|-- Place
BaseModel <|-- Review
BaseModel <|-- Amenity

User "1" --> "0..*" Place : owns
User "1" --> "0..*" Review : writes
Place "1" --> "0..*" Review : has
Place "0..*" --> "0..*" Amenity : includes
